### ISSUE TITLE
Are the used Wikidata Facts limited to the ones existing in the Wikipedia page ? 

### ISSUE THREAD

**Issue by hadyelsahar** [dmorr-google/wiki-reading#10]
How did the authors while generating the dataset guarantee that the answer of the Wikidata triples will exist in the Wikipedia page ? let alone in the first 300 words as most of the existing approaches limit the document to. 
I haven't noticed that in the related publication, thanks !

**Comment by laundry** [comment]
The answer isn't guaranteed to appear in the Wikipedia document text. For
example, the gender relation for person entities will most often not appear
(articles don't directly say male or female).

Also, the answer isn't guaranteed to be inferable from the document. This
would be expensive to verify.
