### ISSUE TITLE
Dataset size doesn't match paper

### ISSUE THREAD

**Issue by atroche** [dmorr-google/wiki-reading#12]
Hi guys,

Thanks for releasing this dataset. I think it'll make a great benchmark for natural language understanding tasks.

In [the paper](https://arxiv.org/abs/1608.03542) it says that the dataset consists of 18.58M instances, and that they were assigned to “training (12.97M instances), validation (1.88M), and test (3.73M ) sets following a 70/10/20 distribution.”

But looking at the numbers from the files I downloaded (and from what's written in the README), it seems that a) there are almost 300,000 extra instances total, and b) the distribution between training / validation / testing is very different.

Any clues? I'm trying to run a different classifier on the categorical properties to compare the results with those in the paper, but it's hard to trust the results when I'm working on different data.

Cheers!

**Comment by laundry** [comment]
Hi Alistair, the answer to your question wasn't immediately obvious to me. One of us (he knows most about this) is out on a long vacation, so I'm going to defer until he comes back. Sorry bout that.

**Comment by danielhewlett** [comment]
After looking into this, it seems that some of the frequency stats in the paper were based on an older internal version of the dataset. I've updated the paper on arXiv with the correct newer stats: https://arxiv.org/abs/1608.03542
