### ISSUE TITLE
Dataset includes blank documents with questions + answers

### ISSUE THREAD

**Issue by atroche** [dmorr-google/wiki-reading#13]
Hi,

There are instances in the JSON files which have a blank document. Is this by design? Were they stripped out in the data eventually used in the WikiReading paper?

By my count there are these many:

* training: 5673
* testing: 318
* validation: 2277

Cheers!

**Comment by danielhewlett** [comment]
Thanks for reporting this. No, these would not be stripped out, although they probably should have been! At this point, we will just consider this a small amount of noise in the dataset.
