### ISSUE TITLE
malformatted JSON in validation-00000-of-00015.json

### ISSUE THREAD

**Issue by robinjia** [dmorr-google/wiki-reading#14]
Line 6322 of validation-00000-of-00015.json is not actually valid JSON.   It looks like something got deleted in the place where "sign2" is.

**Comment by laundry** [comment]
Hi Robin, was this for the English or one of the other languages?

**Comment by robinjia** [comment]
This is for English.  I was pretty surprised so I re-downloaded the zip (https://storage.googleapis.com/wikireading/validation.json.tar.gz) and unzipped it again, and found the same thing.  It looks like there's a few other lines in that file that are also invalid JSON, but all the other files seem fine.

**Comment by laundry** [comment]
Whoa that's weird. Looks like the json writer fused two of the records together. :)

Hope this doesn't block you. I'll check the data generator.

**Comment by laundry** [comment]
Regenerated that broken object and checked that rest of the shards contain valid JSON. Both old and fixed versions of validation-00000-of-00015.json have 126305 objects total.
