### ISSUE TITLE
Documentation could be improved

### ISSUE THREAD

**Issue by karpathy** [dmorr-google/wiki-reading#4]
Hi, thank you for releasing this dataset!

I tried to download and inspect the data but the documentation is quite sparse. For example, unpacking the `validation` tar file gives multiple files, but no documentation as to what they contain, in what encoding or type. In particular, they don't appear to be pickle files.

Thank you!

**Comment by laundry** [comment]
They're TFRecords sharded into a bunch of files. You can use a [TFRecordReader](https://www.tensorflow.org/versions/r0.10/api_docs/python/io_ops.html#TFRecordReader) to open any of the shards. Thanks for the feedback -- I'll add documentation that's more than one sentence. :)

**Comment by laundry** [comment]
Let me know if I should add some more: https://github.com/dmorr-google/wiki-reading/pull/5

**Comment by entron** [comment]
Would be good if the data is stored in a more widely used format such as raw txt, csv etc. In this way no matter which language or tool one uses one can easily access the data.

**Comment by laundry** [comment]
Hi @entron, how about json? We got a few other requests for json, and since each instance is a keyed list or value, it's a better bet over csv. Here they are: https://github.com/dmorr-google/wiki-reading/pull/6

**Comment by entron** [comment]
json is very good, thanks for the update!
